"""baseline postgres — schema único no PostgreSQL (DATABASE_URL via app).

Revision ID: bf635058e244
Revises: 
Create Date: 2026-03-18 15:48:13.153269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf635058e244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_gerencial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_decisao', sa.String(length=50), nullable=False),
    sa.Column('decisao', sa.String(length=255), nullable=True),
    sa.Column('contexto_json', sa.Text(), nullable=True),
    sa.Column('resultado', sa.String(length=50), nullable=True),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria_gerencial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_gerencial_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_gerencial_tipo_decisao'), ['tipo_decisao'], unique=False)

    op.create_table('base_localidades',
    sa.Column('uf_nome', sa.String(length=100), nullable=True),
    sa.Column('cidade_nome', sa.String(length=100), nullable=True),
    sa.Column('chave_busca', sa.String(length=255), nullable=False),
    sa.Column('id_uf', sa.Integer(), nullable=True),
    sa.Column('id_cidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('chave_busca')
    )
    op.create_table('config_regras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor_texto', sa.String(length=500), nullable=True),
    sa.Column('valor_inteiro', sa.Integer(), nullable=True),
    sa.Column('valor_real', sa.Float(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_regras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_regras_chave'), ['chave'], unique=True)

    op.create_table('frete_real',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('id_cidade_origem', sa.Integer(), nullable=True),
    sa.Column('id_uf_origem', sa.Integer(), nullable=True),
    sa.Column('id_cidade_destino', sa.Integer(), nullable=True),
    sa.Column('id_uf_destino', sa.Integer(), nullable=True),
    sa.Column('cidade_origem', sa.String(length=100), nullable=True),
    sa.Column('uf_origem', sa.String(length=2), nullable=True),
    sa.Column('cidade_destino', sa.String(length=100), nullable=True),
    sa.Column('uf_destino', sa.String(length=2), nullable=True),
    sa.Column('peso_real', sa.Float(), nullable=True),
    sa.Column('valor_nf', sa.Float(), nullable=True),
    sa.Column('valor_frete_total', sa.Float(), nullable=True),
    sa.Column('valor_imposto', sa.Float(), nullable=True),
    sa.Column('modal', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insight_canal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('noticia_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.String(length=80), nullable=True),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('impressoes', sa.Integer(), nullable=True),
    sa.Column('cliques', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('leads_gerados', sa.Integer(), nullable=True),
    sa.Column('taxa_conversao', sa.Float(), nullable=True),
    sa.Column('engajamento', sa.Float(), nullable=True),
    sa.Column('score_performance', sa.Float(), nullable=True),
    sa.Column('origem_dado', sa.String(length=20), nullable=True),
    sa.Column('coletado_em', sa.DateTime(), nullable=True),
    sa.Column('processado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insight_canal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insight_canal_canal'), ['canal'], unique=False)
        batch_op.create_index(batch_op.f('ix_insight_canal_coletado_em'), ['coletado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_insight_canal_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insight_canal_noticia_id'), ['noticia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insight_canal_origem_dado'), ['origem_dado'], unique=False)
        batch_op.create_index(batch_op.f('ix_insight_canal_score_performance'), ['score_performance'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('missao_agente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.String(length=80), nullable=False),
    sa.Column('tipo_missao', sa.String(length=50), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('janela_publicacao_inicio', sa.DateTime(), nullable=True),
    sa.Column('janela_publicacao_fim', sa.DateTime(), nullable=True),
    sa.Column('tentativa_atual', sa.Integer(), nullable=True),
    sa.Column('max_tentativas', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('payload_metadados', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('missao_agente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missao_agente_mission_id'), ['mission_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_missao_agente_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_missao_agente_tipo_missao'), ['tipo_missao'], unique=False)

    op.create_table('noticias_portal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('titulo_julia', sa.String(length=255), nullable=False),
    sa.Column('subtitulo', sa.String(length=500), nullable=True),
    sa.Column('titulo_original', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.Column('resumo_julia', sa.Text(), nullable=True),
    sa.Column('conteudo_completo', sa.Text(), nullable=True),
    sa.Column('url_imagem', sa.String(length=500), nullable=True),
    sa.Column('referencias', sa.Text(), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('objetivo_lead', sa.String(length=100), nullable=True),
    sa.Column('status_qualidade', sa.String(length=30), nullable=True),
    sa.Column('origem_pauta', sa.String(length=50), nullable=True),
    sa.Column('url_imagem_master', sa.String(length=500), nullable=True),
    sa.Column('assets_canais_json', sa.Text(), nullable=True),
    sa.Column('status_publicacao', sa.String(length=30), nullable=True),
    sa.Column('publicado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    with op.batch_alter_table('noticias_portal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_noticias_portal_data_publicacao'), ['data_publicacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_noticias_portal_status_publicacao'), ['status_publicacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_noticias_portal_status_qualidade'), ['status_qualidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_noticias_portal_tipo'), ['tipo'], unique=False)

    op.create_table('pautas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo_original', sa.String(length=500), nullable=False),
    sa.Column('fonte', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('mission_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status_verificacao', sa.String(length=30), nullable=True),
    sa.Column('score_confiabilidade', sa.Float(), nullable=True),
    sa.Column('motivo_verificacao', sa.Text(), nullable=True),
    sa.Column('fonte_tipo', sa.String(length=30), nullable=True),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=True),
    sa.Column('coletado_em', sa.DateTime(), nullable=True),
    sa.Column('verificado_em', sa.DateTime(), nullable=True),
    sa.Column('arquivada', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pautas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pautas_arquivada'), ['arquivada'], unique=False)
        batch_op.create_index(batch_op.f('ix_pautas_hash_conteudo'), ['hash_conteudo'], unique=False)
        batch_op.create_index(batch_op.f('ix_pautas_link'), ['link'], unique=True)
        batch_op.create_index(batch_op.f('ix_pautas_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pautas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pautas_status_verificacao'), ['status_verificacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_pautas_tipo'), ['tipo'], unique=False)

    op.create_table('plano_estrategico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema_serie', sa.String(length=255), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('estagio_atual', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plano_estrategico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plano_estrategico_ativo'), ['ativo'], unique=False)

    op.create_table('publicacao_canal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('noticia_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.String(length=80), nullable=True),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('tentativa_atual', sa.Integer(), nullable=True),
    sa.Column('max_tentativas', sa.Integer(), nullable=True),
    sa.Column('payload_envio_json', sa.Text(), nullable=True),
    sa.Column('resposta_canal_json', sa.Text(), nullable=True),
    sa.Column('erro_detalhe', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publicacao_canal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publicacao_canal_canal'), ['canal'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacao_canal_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacao_canal_noticia_id'), ['noticia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacao_canal_status'), ['status'], unique=False)

    op.create_table('recomendacao_estrategica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contexto_json', sa.Text(), nullable=True),
    sa.Column('recomendacao', sa.Text(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recomendacao_estrategica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recomendacao_estrategica_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_recomendacao_estrategica_status'), ['status'], unique=False)

    op.create_table('serie_editorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=False),
    sa.Column('objetivo_lead', sa.String(length=100), nullable=True),
    sa.Column('cta_base', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cadencia_dias', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serie_editorial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serie_editorial_ativo'), ['ativo'], unique=False)

    op.create_table('serie_editorial_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('titulo_planejado', sa.String(length=500), nullable=True),
    sa.Column('subtitulo_planejado', sa.String(length=500), nullable=True),
    sa.Column('data_planejada', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('pauta_id', sa.Integer(), nullable=True),
    sa.Column('noticia_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serie_editorial_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serie_editorial_item_data_planejada'), ['data_planejada'], unique=False)
        batch_op.create_index(batch_op.f('ix_serie_editorial_item_noticia_id'), ['noticia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serie_editorial_item_ordem'), ['ordem'], unique=False)
        batch_op.create_index(batch_op.f('ix_serie_editorial_item_pauta_id'), ['pauta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serie_editorial_item_serie_id'), ['serie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serie_editorial_item_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serie_editorial_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serie_editorial_item_status'))
        batch_op.drop_index(batch_op.f('ix_serie_editorial_item_serie_id'))
        batch_op.drop_index(batch_op.f('ix_serie_editorial_item_pauta_id'))
        batch_op.drop_index(batch_op.f('ix_serie_editorial_item_ordem'))
        batch_op.drop_index(batch_op.f('ix_serie_editorial_item_noticia_id'))
        batch_op.drop_index(batch_op.f('ix_serie_editorial_item_data_planejada'))

    op.drop_table('serie_editorial_item')
    with op.batch_alter_table('serie_editorial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serie_editorial_ativo'))

    op.drop_table('serie_editorial')
    with op.batch_alter_table('recomendacao_estrategica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recomendacao_estrategica_status'))
        batch_op.drop_index(batch_op.f('ix_recomendacao_estrategica_criado_em'))

    op.drop_table('recomendacao_estrategica')
    with op.batch_alter_table('publicacao_canal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publicacao_canal_status'))
        batch_op.drop_index(batch_op.f('ix_publicacao_canal_noticia_id'))
        batch_op.drop_index(batch_op.f('ix_publicacao_canal_mission_id'))
        batch_op.drop_index(batch_op.f('ix_publicacao_canal_canal'))

    op.drop_table('publicacao_canal')
    with op.batch_alter_table('plano_estrategico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_estrategico_ativo'))

    op.drop_table('plano_estrategico')
    with op.batch_alter_table('pautas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pautas_tipo'))
        batch_op.drop_index(batch_op.f('ix_pautas_status_verificacao'))
        batch_op.drop_index(batch_op.f('ix_pautas_status'))
        batch_op.drop_index(batch_op.f('ix_pautas_mission_id'))
        batch_op.drop_index(batch_op.f('ix_pautas_link'))
        batch_op.drop_index(batch_op.f('ix_pautas_hash_conteudo'))
        batch_op.drop_index(batch_op.f('ix_pautas_arquivada'))

    op.drop_table('pautas')
    with op.batch_alter_table('noticias_portal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_noticias_portal_tipo'))
        batch_op.drop_index(batch_op.f('ix_noticias_portal_status_qualidade'))
        batch_op.drop_index(batch_op.f('ix_noticias_portal_status_publicacao'))
        batch_op.drop_index(batch_op.f('ix_noticias_portal_data_publicacao'))

    op.drop_table('noticias_portal')
    with op.batch_alter_table('missao_agente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missao_agente_tipo_missao'))
        batch_op.drop_index(batch_op.f('ix_missao_agente_status'))
        batch_op.drop_index(batch_op.f('ix_missao_agente_mission_id'))

    op.drop_table('missao_agente')
    op.drop_table('leads')
    with op.batch_alter_table('insight_canal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insight_canal_score_performance'))
        batch_op.drop_index(batch_op.f('ix_insight_canal_origem_dado'))
        batch_op.drop_index(batch_op.f('ix_insight_canal_noticia_id'))
        batch_op.drop_index(batch_op.f('ix_insight_canal_mission_id'))
        batch_op.drop_index(batch_op.f('ix_insight_canal_coletado_em'))
        batch_op.drop_index(batch_op.f('ix_insight_canal_canal'))

    op.drop_table('insight_canal')
    op.drop_table('frete_real')
    with op.batch_alter_table('config_regras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_regras_chave'))

    op.drop_table('config_regras')
    op.drop_table('base_localidades')
    with op.batch_alter_table('auditoria_gerencial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_gerencial_tipo_decisao'))
        batch_op.drop_index(batch_op.f('ix_auditoria_gerencial_created_at'))

    op.drop_table('auditoria_gerencial')
    # ### end Alembic commands ###
