"""adiciona user

Revision ID: fa9c6cbc64b7
Revises: f28d05a0c94e
Create Date: 2026-03-19 12:53:11.362998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9c6cbc64b7'
down_revision = 'f28d05a0c94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('subscribes_to_newsletter', sa.Boolean(), nullable=True),
    sa.Column('accepted_terms_at', sa.DateTime(), nullable=True),
    sa.Column('usage_purpose', sa.String(length=50), nullable=True),
    sa.Column('job_role', sa.String(length=100), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_sub', sa.String(length=255), nullable=True),
    sa.Column('chat_consultas_hoje', sa.Integer(), nullable=True),
    sa.Column('chat_data_ultima_consulta', sa.DateTime(), nullable=True),
    sa.Column('trial_start_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
